## Manipulação de Strings com python 
 > Uma variavel primaria de texto é chamada de char ou caracter possibilitando o armazenamento de 8 bit de memória. Quando necessitampos de um conjuto de caracteres utilizamos um onjeto, ou variaveis compostas no caso da maioria das linguagens chamada de string. Vamos ver como se aplica.
 

In [1]:
frase = "Boa tarde a todos"
print (frase) 
saudacao =  frase [0:9]
print (saudacao)

Boa tarde a todos
Boa tarde


In [2]:
print (type(frase))
print (type(saudacao))

<class 'str'>
<class 'str'>


In [15]:
print(frase.count(' '))
print(saudacao.count(' '))


2
1


In [6]:
print(len(frase))
print(len(saudacao))

17
9


In [7]:
frase = frase.replace('a todos','galerinha!')
print(frase)

Boa tarde galerinha!


In [8]:
frase = frase.replace('Boa tarde','Boa noite')
print(frase)

Boa noite galerinha!


In [9]:
saudacao + saudacao.replace('tarde','noite')
print(saudacao)

Boa tarde


In [10]:
frase = [i for i in frase]
print(frase)

['B', 'o', 'a', ' ', 'n', 'o', 'i', 't', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a', '!']


In [12]:
for x in frase:
    print(x)

B
o
a
 
n
o
i
t
e
 
g
a
l
e
r
i
n
h
a
!


## Exercício 1 
> Crie um código para a seguinte frase:"Sabia que o sabiá sabia assubiar" reparticionado por espaços, após issom cire um print format pra visulizar cada palavra em uma coluna separada

In [33]:
frase = "sabia que o sabiá sabia assubiar"

palavras = frase.split()

print(palavras) 



['sabia', 'que', 'o', 'sabiá', 'sabia', 'assubiar']


In [40]:
for i in range(max(len(x)for x in palavras)):
    for y in palavras:
     print(y[i] if i < len(y) else ' ', end =' ')

    print()

s q o s s a 
a u   a a s 
b e   b b s 
i     i i u 
a     á a b 
          i 
          a 
          r 


>segunda forma de fazer

In [41]:
for i in range(max(len (x) for x in palavras)):
    print(' '.join(x [i] if i< len(x) else ' ' for x in palavras))

s q o s s a
a u   a a s
b e   b b s
i     i i u
a     á a b
          i
          a
          r


## Introdução a Numpy
 >Numpy é uma biblioteca python para desenvolvimento de matrizes, Tem por objetivo facilitar na criação de algoritmos metematios para solucionar paradgimas avançados em relação arrays.

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [45]:
b = np.array ([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [48]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [52]:
print(a.max())
print(b.max())
print(c.max())
print(d.max())

3
6
1.0
1.0


In [53]:
print(a.min())
print(b.min())
print(c.min())
print(d.min())

1
1
1.0
0.0


In [54]:
print(a.sum())
print(b.sum())
print(c.sum())
print(d.sum())

6
21
9.0
5.0


In [57]:
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())

2.0
3.5
1.0
0.2


>para desvio padrão

In [60]:
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))
print(round(d.std(),2))

0.82
1.71
0.0
0.4


## Exercicio 2
  > Crie uma matriz chamada contar com os numeros de 0 até 9. Ao final cire uma contragem, média e desvio padrão dessa matriz. Para adicionar de zero e 9 utilize um for e depois atribua á matriz

In [66]:
contar = np.array([1,2,3,5,6,7,8,9])
print(a)

[1 2 3 5 6 7 8 9]


In [67]:
print(contar.mean())

5.125


In [68]:
print(round(contar.std(),2))

2.71
